version: "3.7"
services:
  db:
    hostname: db
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=sample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - "5432:5432"
